<a href="https://colab.research.google.com/github/Mukuta-Manit-D/PYTORCH-MARATHON/blob/main/1_Starting_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Check the package installations and setup GPU Runtime

In [1]:
print("I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!")

I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Tensors are Goddamn basics, Start with that!!!

#### Scalar Tensors

In [4]:
# In these kind of scalar tensors, we store only single elements inside these tensors

scalar = torch.tensor(1)
scalar

tensor(1)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

1

#### Vector Tensors

In [7]:
# In the vector tensors, we store many elements which comprises on dimension basis where we can store magnitude and direction

vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [8]:
vector.dim()

1

In [9]:
vector.shape

torch.Size([2])

#### Matrix Tensors

In [10]:
# Storing tensors when we the data is in the matrix form

matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 3])

In [13]:
print(matrix[1])

tensor([4, 5, 6])


#### Asli Tensors ye hai

In [14]:
TENSORS = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])

In [15]:
TENSORS.shape

torch.Size([1, 3, 3])

In [16]:
TENSORS.ndim

3

## Random Tensors comes to the play now

In [17]:
# Creating a random tensor
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.0872, 0.6590, 0.2018, 0.2978],
        [0.9349, 0.5787, 0.0521, 0.3006],
        [0.3031, 0.9813, 0.6648, 0.1163]])

In [18]:
rand_tensor.ndim

2

In [19]:
# Creating a random dummy tensor that's similar to image tensor

rand_image_tensor = torch.rand(size=(224,224,3))
rand_image_tensor.shape, rand_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones Tensors

In [20]:
# Creating a tensor of all zeroes

zero = torch.zeros(6,6)
zero

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
zero.ndim, zero.shape

(2, torch.Size([6, 6]))

In [22]:
# Creating a tensor of all ones

ones = torch.ones(5,5)
ones.ndim, ones.shape

(2, torch.Size([5, 5]))

In [23]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a Range of Tensors

In [24]:
ran_of_ten = torch.arange(start=0, end=400, step = 3)
ran_of_ten

tensor([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123,
        126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
        168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207,
        210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249,
        252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291,
        294, 297, 300, 303, 306, 309, 312, 315, 318, 321, 324, 327, 330, 333,
        336, 339, 342, 345, 348, 351, 354, 357, 360, 363, 366, 369, 372, 375,
        378, 381, 384, 387, 390, 393, 396, 399])

## Tensor DATATYPES

In [25]:
dt = torch.tensor([1.0,2.0,3.0],
                  dtype=torch.complex32,
                  requires_grad=False)
dt

/tmp/ipython-input-507942186.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:55.)
  dt = torch.tensor([1.0,2.0,3.0],


tensor([1.+0.j, 2.+0.j, 3.+0.j], dtype=torch.complex32)

In [26]:
dt.dtype

torch.complex32

In [27]:
dts = dt.type(torch.float32)
dts, dts.dtype

/tmp/ipython-input-947930112.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at /pytorch/aten/src/ATen/native/Copy.cpp:307.)
  dts = dt.type(torch.float32)


(tensor([1., 2., 3.]), torch.float32)

In [28]:
dts * dt

tensor([1.+0.j, 4.+0.j, 9.+0.j])

In [29]:
dts.shape

torch.Size([3])

In [30]:
print(f"DataType of dts and dt: {dts.dtype} and {dt.dtype}")
print(f"Shape of dts and dt: {dts.shape} and {dt.shape}")
print(f"Device of dts and dt: {dts.device} and {dt.device}")

DataType of dts and dt: torch.float32 and torch.complex32
Shape of dts and dt: torch.Size([3]) and torch.Size([3])
Device of dts and dt: cpu and cpu


## Operations on Tensors

In [31]:
dts.add(dt)

tensor([2.+0.j, 4.+0.j, 6.+0.j])

In [32]:
tr = torch.rand(3,4)
tr

tensor([[0.1653, 0.5778, 0.4124, 0.7072],
        [0.8868, 0.2244, 0.2933, 0.0578],
        [0.5338, 0.5702, 0.0706, 0.9862]])

In [33]:
tr + 10

tensor([[10.1653, 10.5778, 10.4124, 10.7072],
        [10.8868, 10.2244, 10.2933, 10.0578],
        [10.5338, 10.5702, 10.0706, 10.9862]])

In [34]:
tr -10

tensor([[-9.8347, -9.4222, -9.5876, -9.2928],
        [-9.1132, -9.7756, -9.7067, -9.9422],
        [-9.4662, -9.4298, -9.9294, -9.0138]])

In [35]:
tr * 10

tensor([[1.6531, 5.7782, 4.1243, 7.0725],
        [8.8682, 2.2435, 2.9330, 0.5776],
        [5.3378, 5.7022, 0.7064, 9.8619]])

In [36]:
tr / 10

tensor([[0.0165, 0.0578, 0.0412, 0.0707],
        [0.0887, 0.0224, 0.0293, 0.0058],
        [0.0534, 0.0570, 0.0071, 0.0986]])

In [37]:
tr % 10

tensor([[0.1653, 0.5778, 0.4124, 0.7072],
        [0.8868, 0.2244, 0.2933, 0.0578],
        [0.5338, 0.5702, 0.0706, 0.9862]])

In [38]:
tr = torch.add(tr,12)
tr

tensor([[12.1653, 12.5778, 12.4124, 12.7072],
        [12.8868, 12.2244, 12.2933, 12.0578],
        [12.5338, 12.5702, 12.0706, 12.9862]])

In [39]:
a = torch.rand(2,2)
b = torch.rand(2,2)

a, b, torch.matmul(a,b)

(tensor([[0.4965, 0.3855],
         [0.2916, 0.2697]]),
 tensor([[0.0524, 0.7857],
         [0.6396, 0.7449]]),
 tensor([[0.2726, 0.6773],
         [0.1878, 0.4300]]))

In [40]:
a.max()

tensor(0.4965)

In [41]:
a.min()

tensor(0.2697)

In [46]:
torch.mean(a, 1, True)

tensor([[0.4410],
        [0.2806]])