<a href="https://colab.research.google.com/github/Mukuta-Manit-D/PYTORCH-MARATHON/blob/main/1_Starting_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Check the package installations and setup GPU Runtime

In [1]:
print("I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!")

I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Tensors are Goddamn basics, Start with that!!!

#### Scalar Tensors

In [4]:
# In these kind of scalar tensors, we store only single elements inside these tensors

scalar = torch.tensor(1)
scalar

tensor(1)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

1

#### Vector Tensors

In [7]:
# In the vector tensors, we store many elements which comprises on dimension basis where we can store magnitude and direction

vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [8]:
vector.dim()

1

In [9]:
vector.shape

torch.Size([2])

#### Matrix Tensors

In [10]:
# Storing tensors when we the data is in the matrix form

matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 3])

In [13]:
print(matrix[1])

tensor([4, 5, 6])


#### Asli Tensors ye hai

In [14]:
TENSORS = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])

In [15]:
TENSORS.shape

torch.Size([1, 3, 3])

In [16]:
TENSORS.ndim

3

## Random Tensors comes to the play now

In [17]:
# Creating a random tensor
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.1065, 0.7144, 0.4837, 0.2291],
        [0.9296, 0.9701, 0.3337, 0.4371],
        [0.8116, 0.5502, 0.3486, 0.1423]])

In [18]:
rand_tensor.ndim

2

In [19]:
# Creating a random dummy tensor that's similar to image tensor

rand_image_tensor = torch.rand(size=(224,224,3))
rand_image_tensor.shape, rand_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones Tensors

In [20]:
# Creating a tensor of all zeroes

zero = torch.zeros(6,6)
zero

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
zero.ndim, zero.shape

(2, torch.Size([6, 6]))

In [22]:
# Creating a tensor of all ones

ones = torch.ones(5,5)
ones.ndim, ones.shape

(2, torch.Size([5, 5]))

In [23]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a Range of Tensors

In [24]:
ran_of_ten = torch.arange(start=0, end=400, step = 3)
ran_of_ten

tensor([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123,
        126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
        168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207,
        210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249,
        252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291,
        294, 297, 300, 303, 306, 309, 312, 315, 318, 321, 324, 327, 330, 333,
        336, 339, 342, 345, 348, 351, 354, 357, 360, 363, 366, 369, 372, 375,
        378, 381, 384, 387, 390, 393, 396, 399])

## Tensor DATATYPES

In [25]:
dt = torch.tensor([1.0,2.0,3.0],
                  dtype=torch.complex32,
                  requires_grad=False)
dt

/tmp/ipython-input-507942186.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:55.)
  dt = torch.tensor([1.0,2.0,3.0],


tensor([1.+0.j, 2.+0.j, 3.+0.j], dtype=torch.complex32)

In [26]:
dt.dtype

torch.complex32

In [27]:
dts = dt.type(torch.float32)
dts, dts.dtype

/tmp/ipython-input-947930112.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at /pytorch/aten/src/ATen/native/Copy.cpp:307.)
  dts = dt.type(torch.float32)


(tensor([1., 2., 3.]), torch.float32)

In [28]:
dts * dt

tensor([1.+0.j, 4.+0.j, 9.+0.j])

In [29]:
dts.shape

torch.Size([3])

In [30]:
print(f"DataType of dts and dt: {dts.dtype} and {dt.dtype}")
print(f"Shape of dts and dt: {dts.shape} and {dt.shape}")
print(f"Device of dts and dt: {dts.device} and {dt.device}")

DataType of dts and dt: torch.float32 and torch.complex32
Shape of dts and dt: torch.Size([3]) and torch.Size([3])
Device of dts and dt: cpu and cpu


## Operations on Tensors

In [31]:
dts.add(dt)

tensor([2.+0.j, 4.+0.j, 6.+0.j])

In [32]:
tr = torch.rand(3,4)
tr

tensor([[0.1734, 0.5602, 0.2165, 0.7814],
        [0.1705, 0.7231, 0.3763, 0.8479],
        [0.9726, 0.1286, 0.6986, 0.8797]])

In [33]:
tr + 10

tensor([[10.1734, 10.5602, 10.2165, 10.7814],
        [10.1705, 10.7231, 10.3763, 10.8479],
        [10.9726, 10.1286, 10.6986, 10.8797]])

In [34]:
tr -10

tensor([[-9.8266, -9.4398, -9.7835, -9.2186],
        [-9.8295, -9.2769, -9.6237, -9.1521],
        [-9.0274, -9.8714, -9.3014, -9.1203]])

In [35]:
tr * 10

tensor([[1.7336, 5.6019, 2.1650, 7.8138],
        [1.7047, 7.2309, 3.7630, 8.4792],
        [9.7259, 1.2862, 6.9864, 8.7972]])

In [36]:
tr / 10

tensor([[0.0173, 0.0560, 0.0217, 0.0781],
        [0.0170, 0.0723, 0.0376, 0.0848],
        [0.0973, 0.0129, 0.0699, 0.0880]])

In [37]:
tr % 10

tensor([[0.1734, 0.5602, 0.2165, 0.7814],
        [0.1705, 0.7231, 0.3763, 0.8479],
        [0.9726, 0.1286, 0.6986, 0.8797]])

In [38]:
tr = torch.add(tr,12)
tr

tensor([[12.1734, 12.5602, 12.2165, 12.7814],
        [12.1705, 12.7231, 12.3763, 12.8479],
        [12.9726, 12.1286, 12.6986, 12.8797]])

In [39]:
a = torch.rand(2,2)
b = torch.rand(2,2)

a, b, torch.matmul(a,b)

(tensor([[0.7006, 0.6687],
         [0.2846, 0.8558]]),
 tensor([[0.3593, 0.3317],
         [0.9396, 0.5371]]),
 tensor([[0.8801, 0.5915],
         [0.9064, 0.5540]]))

In [40]:
a.max()

tensor(0.8558)

In [41]:
a.min()

tensor(0.2846)

In [42]:
torch.mean(a, 1, True)

tensor([[0.6847],
        [0.5702]])

## Reshaping, Viewing and Stacking Tensors

In [43]:
reshape = torch.arange(1.0, 10., 1)
reshape, reshape.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
reshape = torch.reshape(reshape, [9,1])
reshape.shape
reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

## Converting Numpy Array data to Torch tensors

In [49]:
a = np.arange(1, 100, 2)
t = torch.from_numpy(a)
t, t.dtype

(tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
         37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
         73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]),
 torch.int64)

## Reproducibility

In [59]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
c = torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
d = torch.rand(2,3)
print(c == d)

tensor([[True, True, True],
        [True, True, True]])


In [60]:
c, d

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]))