<a href="https://colab.research.google.com/github/Mukuta-Manit-D/PYTORCH-MARATHON/blob/main/1_Starting_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Check the package installations and setup GPU Runtime

In [1]:
print("I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!")

I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Tensors are Goddamn basics, Start with that!!!

#### Scalar Tensors

In [4]:
# In these kind of scalar tensors, we store only single elements inside these tensors

scalar = torch.tensor(1)
scalar

tensor(1)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

1

#### Vector Tensors

In [7]:
# In the vector tensors, we store many elements which comprises on dimension basis where we can store magnitude and direction

vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [8]:
vector.dim()

1

In [9]:
vector.shape

torch.Size([2])

#### Matrix Tensors

In [10]:
# Storing tensors when we the data is in the matrix form

matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([3, 3])

In [13]:
print(matrix[1])

tensor([4, 5, 6])


#### Asli Tensors ye hai

In [14]:
TENSORS = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])

In [15]:
TENSORS.shape

torch.Size([1, 3, 3])

In [16]:
TENSORS.ndim

3

## Random Tensors comes to the play now

In [17]:
# Creating a random tensor
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.9611, 0.3119, 0.3701, 0.7540],
        [0.9138, 0.8078, 0.9156, 0.8577],
        [0.0544, 0.9163, 0.4129, 0.6096]])

In [18]:
rand_tensor.ndim

2

In [19]:
# Creating a random dummy tensor that's similar to image tensor

rand_image_tensor = torch.rand(size=(224,224,3))
rand_image_tensor.shape, rand_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones Tensors

In [20]:
# Creating a tensor of all zeroes

zero = torch.zeros(6,6)
zero

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [21]:
zero.ndim, zero.shape

(2, torch.Size([6, 6]))

In [22]:
# Creating a tensor of all ones

ones = torch.ones(5,5)
ones.ndim, ones.shape

(2, torch.Size([5, 5]))

In [23]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a Range of Tensors

In [24]:
ran_of_ten = torch.arange(start=0, end=400, step = 3)
ran_of_ten

tensor([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123,
        126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
        168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207,
        210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249,
        252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291,
        294, 297, 300, 303, 306, 309, 312, 315, 318, 321, 324, 327, 330, 333,
        336, 339, 342, 345, 348, 351, 354, 357, 360, 363, 366, 369, 372, 375,
        378, 381, 384, 387, 390, 393, 396, 399])

## Tensor DATATYPES

In [25]:
dt = torch.tensor([1.0,2.0,3.0],
                  dtype=torch.complex32,
                  requires_grad=False)
dt

/tmp/ipython-input-507942186.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:55.)
  dt = torch.tensor([1.0,2.0,3.0],


tensor([1.+0.j, 2.+0.j, 3.+0.j], dtype=torch.complex32)

In [26]:
dt.dtype

torch.complex32

In [27]:
dts = dt.type(torch.float32)
dts, dts.dtype

/tmp/ipython-input-947930112.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at /pytorch/aten/src/ATen/native/Copy.cpp:307.)
  dts = dt.type(torch.float32)


(tensor([1., 2., 3.]), torch.float32)

In [28]:
dts * dt

tensor([1.+0.j, 4.+0.j, 9.+0.j])

In [29]:
dts.shape

torch.Size([3])

In [30]:
print(f"DataType of dts and dt: {dts.dtype} and {dt.dtype}")
print(f"Shape of dts and dt: {dts.shape} and {dt.shape}")
print(f"Device of dts and dt: {dts.device} and {dt.device}")

DataType of dts and dt: torch.float32 and torch.complex32
Shape of dts and dt: torch.Size([3]) and torch.Size([3])
Device of dts and dt: cpu and cpu


## Operations on Tensors

In [31]:
dts.add(dt)

tensor([2.+0.j, 4.+0.j, 6.+0.j])

In [32]:
tr = torch.rand(3,4)
tr

tensor([[0.8739, 0.5839, 0.5340, 0.3705],
        [0.8040, 0.8524, 0.2599, 0.4125],
        [0.9287, 0.0042, 0.6491, 0.8680]])

In [33]:
tr + 10

tensor([[10.8739, 10.5839, 10.5340, 10.3705],
        [10.8040, 10.8524, 10.2599, 10.4125],
        [10.9287, 10.0042, 10.6491, 10.8680]])

In [34]:
tr -10

tensor([[-9.1261, -9.4161, -9.4660, -9.6295],
        [-9.1960, -9.1476, -9.7401, -9.5875],
        [-9.0713, -9.9958, -9.3509, -9.1320]])

In [35]:
tr * 10

tensor([[8.7388, 5.8393, 5.3398, 3.7047],
        [8.0395, 8.5237, 2.5993, 4.1253],
        [9.2865, 0.0417, 6.4909, 8.6795]])

In [36]:
tr / 10

tensor([[0.0874, 0.0584, 0.0534, 0.0370],
        [0.0804, 0.0852, 0.0260, 0.0413],
        [0.0929, 0.0004, 0.0649, 0.0868]])

In [37]:
tr % 10

tensor([[0.8739, 0.5839, 0.5340, 0.3705],
        [0.8040, 0.8524, 0.2599, 0.4125],
        [0.9287, 0.0042, 0.6491, 0.8680]])

In [38]:
tr = torch.add(tr,12)
tr

tensor([[12.8739, 12.5839, 12.5340, 12.3705],
        [12.8040, 12.8524, 12.2599, 12.4125],
        [12.9287, 12.0042, 12.6491, 12.8680]])

In [39]:
a = torch.rand(2,2)
b = torch.rand(2,2)

a, b, torch.matmul(a,b)

(tensor([[0.0023, 0.5521],
         [0.3274, 0.4388]]),
 tensor([[0.7999, 0.8462],
         [0.4140, 0.8667]]),
 tensor([[0.2304, 0.4804],
         [0.4436, 0.6574]]))

In [40]:
a.max()

tensor(0.5521)

In [41]:
a.min()

tensor(0.0023)

In [42]:
torch.mean(a, 1, True)

tensor([[0.2772],
        [0.3831]])

## Reshaping, Viewing and Stacking Tensors

In [44]:
reshape = torch.arange(1.0, 10., 1)
reshape, reshape.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
reshape = torch.reshape(reshape, [9,1])
reshape.shape
reshape

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])