<a href="https://colab.research.google.com/github/Mukuta-Manit-D/PYTORCH-MARATHON/blob/main/1_Starting_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Check the package installations and setup GPU Runtime

In [ ]:
print("I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!")

I'll learn pytorch in such a way that I must feel I'm the picasso of it!!!


In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


## Tensors are Goddamn basics, Start with that!!!

#### Scalar Tensors

In [ ]:
# In these kind of scalar tensors, we store only single elements inside these tensors

scalar = torch.tensor(1)
scalar

tensor(1)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

1

#### Vector Tensors

In [ ]:
# In the vector tensors, we store many elements which comprises on dimension basis where we can store magnitude and direction

vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
vector.dim()

1

In [ ]:
vector.shape

torch.Size([2])

#### Matrix Tensors

In [ ]:
# Storing tensors when we the data is in the matrix form

matrix = torch.tensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([3, 3])

In [ ]:
print(matrix[1])

tensor([4, 5, 6])


#### Asli Tensors ye hai

In [ ]:
TENSORS = torch.tensor([[[1,2,3],
                         [4,5,6],
                         [7,8,9]]])

In [ ]:
TENSORS.shape

torch.Size([1, 3, 3])

In [ ]:
TENSORS.ndim

3

## Random Tensors comes to the play now

In [ ]:
# Creating a random tensor
rand_tensor = torch.rand(3,4)
rand_tensor

tensor([[0.5379, 0.8098, 0.4798, 0.2579],
        [0.6439, 0.5749, 0.0936, 0.3417],
        [0.8665, 0.3639, 0.1845, 0.8522]])

In [ ]:
rand_tensor.ndim

2

In [ ]:
# Creating a random dummy tensor that's similar to image tensor

rand_image_tensor = torch.rand(size=(224,224,3))
rand_image_tensor.shape, rand_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeroes and Ones Tensors

In [ ]:
# Creating a tensor of all zeroes

zero = torch.zeros(6,6)
zero

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [ ]:
zero.ndim, zero.shape

(2, torch.Size([6, 6]))

In [ ]:
# Creating a tensor of all ones

ones = torch.ones(5,5)
ones.ndim, ones.shape

(2, torch.Size([5, 5]))

In [ ]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

## Creating a Range of Tensors

In [2]:
ran_of_ten = torch.arange(start=0, end=400, step = 3)
ran_of_ten

tensor([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,  78,  81,
         84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114, 117, 120, 123,
        126, 129, 132, 135, 138, 141, 144, 147, 150, 153, 156, 159, 162, 165,
        168, 171, 174, 177, 180, 183, 186, 189, 192, 195, 198, 201, 204, 207,
        210, 213, 216, 219, 222, 225, 228, 231, 234, 237, 240, 243, 246, 249,
        252, 255, 258, 261, 264, 267, 270, 273, 276, 279, 282, 285, 288, 291,
        294, 297, 300, 303, 306, 309, 312, 315, 318, 321, 324, 327, 330, 333,
        336, 339, 342, 345, 348, 351, 354, 357, 360, 363, 366, 369, 372, 375,
        378, 381, 384, 387, 390, 393, 396, 399])

## Tensor DATATYPES

In [14]:
dt = torch.tensor([1.0,2.0,3.0],
                  dtype=torch.complex32,
                  requires_grad=False)
dt

/tmp/ipython-input-507942186.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:55.)
  dt = torch.tensor([1.0,2.0,3.0],


tensor([1.+0.j, 2.+0.j, 3.+0.j], dtype=torch.complex32)

In [15]:
dt.dtype

torch.complex32

In [16]:
dts = dt.type(torch.float32)
dts, dts.dtype

/tmp/ipython-input-947930112.py:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at /pytorch/aten/src/ATen/native/Copy.cpp:307.)
  dts = dt.type(torch.float32)


(tensor([1., 2., 3.]), torch.float32)

In [17]:
dts * dt

tensor([1.+0.j, 4.+0.j, 9.+0.j])

In [18]:
dts.shape

torch.Size([3])

In [23]:
print(f"DataType of dts and dt: {dts.dtype} and {dt.dtype}")
print(f"Shape of dts and dt: {dts.shape} and {dt.shape}")
print(f"Device of dts and dt: {dts.device} and {dt.device}")

DataType of dts and dt: torch.float32 and torch.complex32
Shape of dts and dt: torch.Size([3]) and torch.Size([3])
Device of dts and dt: cpu and cpu


## Operations on Tensors

In [24]:
dts.add(dt)

tensor([2.+0.j, 4.+0.j, 6.+0.j])

In [32]:
tr = torch.rand(3,4)
tr

tensor([[0.3909, 0.8876, 0.3933, 0.9607],
        [0.0985, 0.9968, 0.4191, 0.8906],
        [0.6353, 0.8147, 0.4968, 0.4990]])

In [33]:
tr + 10

tensor([[10.3909, 10.8876, 10.3933, 10.9607],
        [10.0985, 10.9968, 10.4191, 10.8906],
        [10.6353, 10.8147, 10.4968, 10.4990]])

In [34]:
tr -10

tensor([[-9.6091, -9.1124, -9.6067, -9.0393],
        [-9.9015, -9.0032, -9.5809, -9.1094],
        [-9.3647, -9.1853, -9.5032, -9.5010]])

In [35]:
tr * 10

tensor([[3.9090, 8.8763, 3.9330, 9.6070],
        [0.9854, 9.9681, 4.1906, 8.9056],
        [6.3527, 8.1469, 4.9679, 4.9898]])

In [38]:
tr / 10

tensor([[0.0391, 0.0888, 0.0393, 0.0961],
        [0.0099, 0.0997, 0.0419, 0.0891],
        [0.0635, 0.0815, 0.0497, 0.0499]])

In [39]:
tr % 10

tensor([[0.3909, 0.8876, 0.3933, 0.9607],
        [0.0985, 0.9968, 0.4191, 0.8906],
        [0.6353, 0.8147, 0.4968, 0.4990]])

In [40]:
tr = torch.add(tr,12)
tr

tensor([[12.3909, 12.8876, 12.3933, 12.9607],
        [12.0985, 12.9968, 12.4191, 12.8906],
        [12.6353, 12.8147, 12.4968, 12.4990]])

In [48]:
a = torch.rand(2,2)
b = torch.rand(2,2)

a, b, torch.matmul(a,b)

(tensor([[0.1472, 0.1678],
         [0.5488, 0.4629]]),
 tensor([[0.3932, 0.8408],
         [0.4154, 0.2931]]),
 tensor([[0.1276, 0.1729],
         [0.4081, 0.5972]]))